FROM image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven
#FROM registry.redhat.io/openshift4/ose-jenkins-agent-maven

MAINTAINER Osa Ora

#ENV GRADLE_VERSION=6.8-rc-4
ENV GRADLE_VERSION=6.7.1

USER root

RUN curl -skL -o /tmp/gradle-bin.zip https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip && \
    mkdir -p /opt/gradle && \
    unzip -q /tmp/gradle-bin.zip -d /opt/gradle && \
    ln -sf /opt/gradle/gradle-$GRADLE_VERSION/bin/gradle /usr/local/bin/gradle

RUN chown -R 1001:0 /opt/gradle && \
    chmod -R g+rw /opt/gradle

USER 1001
